version: '3'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    environment:
      - TZ=AST
    #  - PLEX_CLAIM=<claimToken>
    volumes:
      - /home/weinberg/plex/config:/config
      - /tmp:/transcode
      - /mnt/f/shares/movies:/movies
      - /mnt/f/shares/tv:/tv
    networks:
      - dave_network
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp

networks:
  dave_network:
